services:
  db:
    image: postgres:15
    container_name: resume_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: resume_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DB_HOST: db   # переопределяем DB_HOST только внутри контейнера
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
